### ISSUE TITLE
Arrows bug?

### ISSUE THREAD

**Issue by ImaniB738** [LunaPixelStudios/Better-MC#1410]
### Describe the Bug

Cannot craft regular arrows using flint, sticks, and feathers. Only includes recipe for modded items

![image](https://github.com/LunaPixelStudios/Better-MC/assets/102762118/4774f71b-5cb8-4863-b467-b2910acf5a56)

### Reproduction Steps

1.Place items in crafting table (flint in top slot, stick in middle slot, feather in bottom slot)
2. Arrow craft does not come up 
3. Arrow recipe also does not show in crafting table recipes
...

### Screenshots and Videos

![Screenshot 2023-09-28 202745](https://github.com/LunaPixelStudios/Better-MC/assets/102762118/0e915f10-6c2a-49a4-8d44-4a91cf53c0f8)
![Screenshot 2023-09-28 203028](https://github.com/LunaPixelStudios/Better-MC/assets/102762118/656810d7-0249-4fc2-b91f-3285a6c05328)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

bmc3 v18

### Other Mods

Inventory Crafter by LegoMaster3650

**Comment by SHXRKIIE** [comment]
Fixed in new update

**Comment by ImaniB738** [comment]
Unfortunately, I still cannot craft using the regular arrow recipe
