### ISSUE TITLE
Some Textures are not working like they used too

### ISSUE THREAD

**Issue by Stoneyseth** [LunaPixelStudios/Better-MC#1773]
### Describe the Bug

i have smooth sea lanterns around my farm and i noticed after the update that look like normal sea lanterns again. i tried re crafting them into smooth sea lanterns but nothing changed. in my inventory they look correct but when placed they go back to the original texture.

### Reproduction Steps

1.
2.
3.
...

### Operating System

windows 11

### Minecraft Version

1.20.1

### Modloader

Forge

### Modpack Version

v29.5

### Other Mods

![image_2024-08-04_121910331](https://github.com/user-attachments/assets/5362add9-b0b2-4f95-a222-65d82dbc7f2f)
![image_2024-08-04_121935634](https://github.com/user-attachments/assets/d7ee4a2f-a3b5-49a3-b763-57c47f56aef1)

**Comment by Stoneyseth** [comment]
this mod in the modpack is chipped for the sea lanterns but ive seen other textures change like runlights from the aether redux mod.

**Comment by chorbintime** [comment]
update to v30, we offer no support for old versions

the issue should be fixed by doing a fresh install on ATLauncher

**Comment by Stoneyseth** [comment]
Fresh install on ATLauncher I don't have that program are you saying i should delete it from cursforge and download it via ATLauncher?

**Comment by Stoneyseth** [comment]
I installed ATLauncher and downloaded the modpack and launched it via ATLauncher and it still didn't fix the texture issue.
