### ISSUE TITLE
ServerHangWatchdog detected that a single server tick took 12.00 seconds (should be max 0.05)

### ISSUE THREAD

**Issue by OmikronOverload** [LunaPixelStudios/Better-MC#896]
### Describe the Bug

After travelling trough the Nether, i made a nether portal to the Overworld.
Server crashes, when entering trough the portal.
When i join now it makes the server Crash.

### Reproduction Steps

1.Travel a long Distance trough the Nether
2. Create a new Nether Portal
3. Enter the Portal
...

### Screenshots and Videos

https://user-images.githubusercontent.com/69091958/205494537-2be71e56-6f89-4a7b-b9e8-23e9813b0147.mp4

### Crash Report or Log

[crash-reports_crash-2022-12-04_12.51.39-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10148566/crash-reports_crash-2022-12-04_12.51.39-server.txt)

### Operating System

Windows 11

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Forge 1.19.2 (Verv10.5)

### Optifine

No

### Other Mods

No mods added, but Updated Open parties and Claims due to a Bug creating Ticking entities when the spawn certain particles.

You can read it here.
https://github.com/thexaero/open-parties-and-claims/issues/174#issuecomment-1335268305

**Comment by xSHXRKIEx** [comment]
Remove the mod whatareyouvotingfor and it should fix it

**Comment by OmikronOverload** [comment]
As expected, this didnt fix the Problem unfortunately.
[crash-2022-12-04_15.20.11-server.txt](https://github.com/LunaPixelStudios/Better-MC/files/10148897/crash-2022-12-04_15.20.11-server.txt)

**Comment by OmikronOverload** [comment]
Also changing position in the nbt data doesnt seem to work as well
